name: sweet_shop_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  animated_number: ^1.0.2
  path_provider: ^2.1.2
  image_picker:
  shared_preferences:
  device_info_plus:
  keyboard_actions:
  flutter_staggered_animations:
  file_picker: ^6.1.1
  textfield_search:
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^20.3.56
  syncfusion_flutter_charts:
  flutter_localizations:
    sdk: flutter
  json_annotation:
  internet_connection_checker: ^0.0.1+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  skeleton_text:


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
  fonts:
    - family: OutFit_Black_Font
      fonts:
        - asset: assets/fonts/outfit_bold.ttf
    - family: OutFit_SemiBold_Font
      fonts:
        - asset: assets/fonts/outfit_semibold.ttf
    - family: OutFit_Medium_Font
      fonts:
        - asset: assets/fonts/outfit_medium.ttf
    - family: OutFit_Regular_Font
      fonts:
        - asset: assets/fonts/outfit_regular.ttf
    - family: OutFit_Black_Font
      fonts:
        - asset: assets/fonts/outfit_black.ttf
    - family: Roboto_Medium_Font
      fonts:
        - asset: assets/fonts/roboto_medium.ttf
    - family: Roboto_Regular_Font
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: Roboto_Bold_Font
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
    - family: Roboto_Light_Font
      fonts:
        - asset: assets/fonts/roboto_light.ttf
    - family: Roboto_Thin_Font
      fonts:
        - asset: assets/fonts/roboto_thin.ttf
    - family: Inter_Bold_Font
      fonts:
        - asset: assets/fonts/Inter_Bold.ttf
    - family: Inter_Medium_Font
      fonts:
        - asset: assets/fonts/Inter_Medium.ttf
    - family: Inter_Regular_Font
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
    - family: Inter_Light_Font
      fonts:
        - asset: assets/fonts/Inter_Light.ttf
    - family: Inter_SemiBold_Font
      fonts:
        - asset: assets/fonts/Inter_SemiBold.ttf
    - family: Archivo_Black
      fonts:
        - asset: assets/fonts/Archivo_Black.ttf
    - family: Archivo_Bold
      fonts:
        - asset: assets/fonts/Archivo_Bold.ttf
    - family: Archivo_Light
      fonts:
        - asset: assets/fonts/Archivo_Light.ttf
    - family: Archivo_Medium
      fonts:
        - asset: assets/fonts/Archivo_Medium.ttf
    - family: Archivo_Regular
      fonts:
        - asset: assets/fonts/Archivo_Regular.ttf
    - family: Archivo_SemiBold
      fonts:
        - asset: assets/fonts/Archivo_SemiBold.ttf
